server:
  port: 8080  # Or whatever Render uses (optional)

spring:
  datasource:
    url: jdbc:postgresql://dpg-d1tt08c9c44c73cdku8g-a.oregon-postgres.render.com/quizdb_191p
    username: quizdb_191p_user
    password: vSngqcEr9IS9J3w7ePMqkYKkpGFP9IYj
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false