spring:
  profiles:
    active: prod  # Change to 'prod' when deploying to Render or use ENV var

openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: private-key

cohere:
  api:
    url: https://api.cohere.ai/v1/generate
    key: KETruJJQArW5K4cYrV62QS3KsRqvWwa2RvwVSFRm

jwt:
  secret: KJd83^maL#P2!c9vNQwZx7EfsT@RMbVp