server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: mohdayaan
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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

cohere:
  api:
    url: https://api.cohere.ai/v1/generate
    key: KETruJJQArW5K4cYrV62QS3KsRqvWwa2RvwVSFRm