server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: mohdayaan
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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